# -*- coding: utf-8 -*-
"""Actividad N° 6 Cuenta_Fernandez_Jeremias.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14KfOKVdXjDJmOK1zpBxT3br4hWhaKbmM
"""

class Cuenta:
    def __init__(self, titular, cantidad):
        self.titular = titular
        self.cantidad = cantidad
        if cantidad<0:
          print(f"Su saldo esta en negativo y es: ${self.cantidad}.")
    def mostrarDatos(self):
      print(f"Titular de la cuenta: {self.titular}. Saldo: ${self.cantidad}.")
    def ingresarSaldo(self,cantidad):
      if cantidad>=0:
        self.cantidad+=cantidad
        print(f"Ingresó: ${cantidad}. Su saldo es: ${self.cantidad}.")
        return self.cantidad
      else:
        print("Error al ingresar el dinero")
    def retirarSaldo(self,cantidad):
      self.cantidad-=cantidad
      print(f"Retiró: ${cantidad}. Su saldo es: ${self.cantidad}")
      return self.cantidad
titular1=Cuenta("Raul Funes",500)
titular1.mostrarDatos()
titular1.ingresarSaldo(100)
titular1.retirarSaldo(50)
titular1.mostrarDatos()